# Generated by Django 3.1.1 on 2020-10-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='titlexp',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
